### ISSUE TITLE
signum

### ISSUE THREAD

**Issue by Hexstream** [defaultxr/mutility#1]
I saw [your `sign` function](https://github.com/defaultxr/mutility/blob/9e52004d26b53066954fb4f5e3e4efa19f88fc72/mutility.lisp#L129-L134) and was wondering if you are aware of standard [signum](http://www.lispworks.com/documentation/HyperSpec/Body/f_signum.htm).

**Comment by defaultxr** [comment]
I was not! I should've figured CL had something like that built in. Thanks for letting me know about it.
