### ISSUE TITLE
Reference to ql package breaks build

### ISSUE THREAD

**Issue by quicklisp** [defaultxr/mutility#4]
https://github.com/defaultxr/mutility/blob/b695e3648bbc03b2995255f2a58bd4a21932be3b/src/test-helpers.lisp#L74

Quicklisp is not part of the quicklisp testing environment, so this system won't compile with the QL reference.

**Comment by defaultxr** [comment]
I knew this but I guess I forgot when I made that change. This should be fixed now, sorry again for the bother.
