### ISSUE TITLE
error: Component #:TRIVIAL-DO not found, required by #<SYSTEM "mutility/loopy">

### ISSUE THREAD

**Issue by TatriX** [defaultxr/mutility#6]
Hi! After recent update I'm getting an error:
```
error: Component #:TRIVIAL-DO not found, required by #<SYSTEM "mutility/loopy">
```

**Comment by defaultxr** [comment]
Which commit are you on currently? Commit f5f9096a21835b38212242800bd73790b68a46e2 is the one that switched to using `trivial-do` and it is listed in the `:depends-on` of `mutility/loopy` in that commit. So I'm not sure why you'd be getting that error if you're using that commit.

**Comment by defaultxr** [comment]
Also, does this error occur just when you do `(ql:quickload 'mutility/loopy)` or are you doing something else when it occurs?

**Comment by TatriX** [comment]
It started happening after I've updated `sbcl`. It retriggered recompilation of packages which gave me an error. I did `git pull` and I'm on `f5f9096`.

> Also, does this error occur just when you do `(ql:quickload 'mutility/loopy)` or are you doing something else when it occurs?

I don't think I require `mutility` anywhere, so I think it happened due to me loading a system which depends on `cl-patterns`.

**Comment by TatriX** [comment]
I've tried reproducing the problem by removing  `.cache/common-lisp` and `:trivial-do` which I installed manually to fix the problem, and error doesn't show up anymore. Sorry for the false alarm!
