### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [defaultxr/mutility#7]
Building with SBCL 2.0.5 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id b35855d034f3d9b4d2f75b81703188887c2ffc91

*mutility* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package CLOSER-MOP does not exist. Line: 233, Column: 54, File-Position: 9530 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/mutility/1a95c097a188544cc49315604c6f0fbe03004b9c/mutility-20210806-git/src/mutility.lisp" {1005EE60D3}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A20083}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "mutility" "mutility">

```

*mutility/loopy* fails to build because of a failure in  _mutility_.

*mutility/test-helpers* fails to build because of a failure in  _mutility_.

*mutility/tests* fails to build because of a failure in  _mutility_.

[Full log here](http://report.quicklisp.org/2021-08-06/failure-report/mutility.html)

**Comment by defaultxr** [comment]
Oops, I forgot to add closer-mop as a dependency. I force-pushed a corrected commit that includes it in the system's `depends-on`, which should resolve this issue.
