### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [defaultxr/mutility#8]
Building with SBCL 2.2.3.124-6aa1cd97b-WIP / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 782aa95c6abb801db65a373fd1837bf3d12cd453

*mutility* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Comma not inside a backquote. Line: 974, Column: 54, File-Position: 38921 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/mutility/aedde29e49fdb71d24a06a07fd6d1c0f8e6704f6/mutility-20220411-git/src/mutility.lisp" {100642D863}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BD0003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "mutility" "mutility">

```

*mutility/loopy* fails to build because of a failure in  _mutility_.

*mutility/test-helpers* fails to build because of a failure in  _mutility_.

*mutility/tests* fails to build because of a failure in  _mutility_.

[Full log here](http://report.quicklisp.org/2022-04-11/failure-report/mutility.html)

**Comment by defaultxr** [comment]
I think this should be fixed now, let me know if not.
