### ISSUE TITLE
Using non-standard characters gives error on other implementations

### ISSUE THREAD

**Issue by Yehouda** [defaultxr/mutility#9]
https://github.com/defaultxr/mutility/blob/c5cae25039304631f38e73c244d832661cbf3ade/src/mutility.lisp#L596

The characters in this list are non-standard, and would give errors on other Lisp implementation. 
Certainly errors on LispWorks.

**Comment by defaultxr** [comment]
Hmm... Unfortunate that the characters can't be specified by name in a portable way. I guess the next best thing would be to specify them by their unicode codepoint with comments specifying their name. I'll push a fix for that soon.
